# Site settings
title: Clean
email: 993013090@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/xueleitt/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xuelei
github_username:  xuelei

# Build settings
markdown: kramdown
